[project]
name = "ml-baseline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "numpy>=2.4.1",
    "polars>=1.37.1",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
